# Generated by Django 5.0.4 on 2024-04-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.ImageField(upload_to='images/')),
                ('text', models.CharField(max_length=150)),
                ('date_public', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
